### ISSUE TITLE
Pysptk setup question,discussion

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [bigpon/QPPWG#3]
I tried to setup qppwg with python venv.
During which it pysptk seems to need window c build tools
What is you envvar used for the window c build tools?
I had a local copy of those c build tools,but I did not setup the env var.
So need your env var as a reference.
Side update,the java port does not seems to go too well.But,will try my best.

**Comment by bigpon** [comment]
I export my conda environment as follows:
"""
name: QPPWG
channels:
- soumith
- defaults

dependencies:
- _libgcc_mutex=0.1=main
- ca-certificates=2020.1.1=0
- certifi=2020.4.5.1=py36_0
- libgcc-ng=9.1.0=hdf63c60_0
- openssl=1.0.2u=h7b6447c_0
- pip=20.0.2=py36_3
- python=3.6.0=0
- readline=6.2=2
- setuptools=46.4.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.34.2=py36_0
- xz=5.2.5=h7b6447c_0
- zlib=1.2.11=h7b6447c_3

prefix: /home/myname/anaconda3/envs/QPPWG

"""
I create this environment on a server with Ubuntu 18.04.5.

If you still cannot install "pysptk", you may ask help from the master author of "pysptk" (https://github.com/r9y9/pysptk).

**Comment by xwaeaewcrhomesysplug** [comment]
I noted we(windows) need to install specific numpy rather than most recent.pip install numpy==1.19.3
Now...Well gotta boot up my iso.I am too lazy to solve this in windows so just gonna close this.
I also asked the pysptk.Well,let's see when they will reply.
