### ISSUE TITLE
How to use this model for Speech Synthesis

### ISSUE THREAD

**Issue by spolezhaev** [bigpon/QPPWG#5]
As I understood from the paper and the provided code, f0 features are extracted from the ground-truth audiofile. However, for the task of speech synthesis it is impossible to get such features as acoustic model only outputs mel-spectrogram. So this vocoder is only applicable for cases when there is an input audio file, for ex. the Voice Conversion task. Am I right or I understand it totally wrong?

**Comment by bigpon** [comment]
Hi @Piteryo,
QPPWG needs the F0 values, but the F0 values can be obtained from input speech/audio or an F0 predictor.
For many conventional TTS systems, the F0 values are predicted using an F0 predictor.

However, the current SOTA TTS models such as Tacotron predict only mel-spectrograms, which entangle F0, harmonic, and spectral information. 
Therefore, if you want to use QPPWG for them, you need to develop an extra F0 predictor or disentangle the F0 information from the predicted mel-spectrograms.

**Comment by spolezhaev** [comment]
@bigpon Thank you a lot. Everything is clear now.
